// Teaching staff of Govt. Graduate College Satellite Town, Rawalpindi (from the college staff statement).
// Names, designation and subject only — no personal details.
const STAFF = [
  {"name": "Prof. Ather Qaseem", "designation": "Principal", "subject": "Urdu"},
  {"name": "Dr. Muhammad Nadim Aslam", "designation": "Professor", "subject": "Urdu"},
  {"name": "Dr. Bushra Parveen", "designation": "Professor", "subject": "Biology"},
  {"name": "Dr. Fayyaz Ahmad Faizi", "designation": "Professor", "subject": "Urdu"},
  {"name": "Prof. Nadeem Khan", "designation": "Associate Professor", "subject": "Botany"},
  {"name": "Dr. Ateeq ul Jaleel", "designation": "Associate Professor", "subject": "Zoology"},
  {"name": "Prof. Asif Raza Rizvi", "designation": "Associate Professor", "subject": "Statistics"},
  {"name": "Prof. Javaid Iqbal", "designation": "Associate Professor", "subject": "Statistics"},
  {"name": "Prof. Saeed Ahmed", "designation": "Associate Professor", "subject": "Arabic"},
  {"name": "Prof. Amin Iqbal", "designation": "Associate Professor", "subject": "Statistics"},
  {"name": "Prof. Khalid Iqbal", "designation": "Associate Professor", "subject": "Physics"},
  {"name": "Prof. M. Kamran Saleem", "designation": "Associate Professor", "subject": "Physics"},
  {"name": "Prof. Muhammad Tayyab", "designation": "Associate Professor", "subject": "History"},
  {"name": "Prof. Abdul Majeed Asif", "designation": "Associate Professor", "subject": "Geography"},
  {"name": "Prof. Abaid Ullah Tariq", "designation": "Associate Professor", "subject": "Islamiat"},
  {"name": "Prof. Faiza Yousaf", "designation": "Associate Professor", "subject": "English"},
  {"name": "Prof. Saima Amjad", "designation": "Associate Professor", "subject": "Physics"},
  {"name": "Prof. Sonia Bukhari", "designation": "Associate Professor", "subject": "English"},
  {"name": "Prof. Anwar ul Islam Qureshi", "designation": "Associate Professor", "subject": "Arabic"},
  {"name": "Prof. Fouzia Siddique", "designation": "Associate Professor", "subject": "Chemistry"},
  {"name": "Prof. Muhammad Shabbir", "designation": "Associate Professor", "subject": "Chemistry"},
  {"name": "Prof. Abdul Ghaffar Anjum", "designation": "Associate Professor", "subject": "Biology"},
  {"name": "Prof. Muhammad Tariq Siddique", "designation": "Associate Professor", "subject": "Economics"},
  {"name": "Prof. Amjad Zia", "designation": "Associate Professor", "subject": "Urdu"},
  {"name": "Prof. Naveed Ullah Arif", "designation": "Associate Professor", "subject": ""},
  {"name": "Prof. Irum Riaz", "designation": "Associate Professor", "subject": ""},
  {"name": "Prof. Nazia Latif", "designation": "Associate Professor", "subject": ""},
  {"name": "Prof. Naseer Ahmed Ansir", "designation": "Associate Professor", "subject": ""},
  {"name": "Prof. Salah-ud-Ahmad Khan Niazi", "designation": "Associate Professor", "subject": ""},
  {"name": "Prof. Asif Abbas", "designation": "Associate Professor", "subject": ""},
  {"name": "Dr. Muhammad Raees", "designation": "Assistant Professor", "subject": "Mathematics"},
  {"name": "Prof. Saadat Ali Khan", "designation": "Assistant Professor", "subject": "Economics"},
  {"name": "Prof. Imran Ejaz", "designation": "Assistant Professor", "subject": "Economics"},
  {"name": "Prof. Fazal Mehmood", "designation": "Assistant Professor", "subject": "English"},
  {"name": "Prof. Syed M. Tahir Shah", "designation": "Assistant Professor", "subject": "Islamiat"},
  {"name": "Prof. Mujahid Abas", "designation": "Assistant Professor", "subject": "Chemistry"},
  {"name": "Prof. Khuram Dad", "designation": "Assistant Professor", "subject": "English"},
  {"name": "Prof. Muhammad Asif Ali", "designation": "Assistant Professor", "subject": "Physics"},
  {"name": "Prof. Muhammad Imran Bashir", "designation": "Assistant Professor", "subject": "Physics"},
  {"name": "Prof. Tasadduq Hussain", "designation": "Assistant Professor", "subject": "English"},
  {"name": "Prof. Hina Irshad", "designation": "Assistant Professor", "subject": "Economics"},
  {"name": "Prof. Safia Nadeem", "designation": "Assistant Professor", "subject": "English"},
  {"name": "Prof. Muhammad Asghar", "designation": "Assistant Professor", "subject": "Physics"},
  {"name": "Prof. Malik Muhammad Iqbal", "designation": "Assistant Professor", "subject": "English"},
  {"name": "Prof. Ashar Shahzad", "designation": "Assistant Professor", "subject": "Statistics"},
  {"name": "Prof. Amir Zia", "designation": "Assistant Professor", "subject": ""},
  {"name": "Prof. Samreen Sajid Amin", "designation": "Assistant Professor", "subject": "Chemistry"},
  {"name": "Prof. Bibi Hajra", "designation": "Assistant Professor", "subject": "Physics"},
  {"name": "Prof. Abdul Jabbar", "designation": "Assistant Professor", "subject": "Mathematics"},
  {"name": "Prof. Muhammad Asif", "designation": "Assistant Professor", "subject": "Physics"},
  {"name": "Prof. Aamir Hayat", "designation": "Assistant Professor", "subject": "Political Science"},
  {"name": "Prof. Zia-Ur-Rehman", "designation": "Assistant Professor", "subject": "Urdu"},
  {"name": "Prof. Muhammad Nazim", "designation": "Assistant Professor", "subject": "Political Science"},
  {"name": "Dr. Muhammad Ismaeel", "designation": "Assistant Professor", "subject": "English"},
  {"name": "Prof. Nadia Zahir Babur", "designation": "Assistant Professor", "subject": "Mathematics"},
  {"name": "Prof. Aisha Rehmat", "designation": "Assistant Professor", "subject": "English"},
  {"name": "Prof. Muhammad Muttaher Bashir", "designation": "Assistant Professor", "subject": "History"},
  {"name": "Prof. Munib Ali Bukhari", "designation": "Assistant Professor", "subject": ""},
  {"name": "Prof. Nadeem Asghar Khan", "designation": "Assistant Professor", "subject": "Chemistry"},
  {"name": "Prof. Ejaz Sallamat", "designation": "Assistant Professor", "subject": ""},
  {"name": "Prof. Saqib Munawar", "designation": "Assistant Professor", "subject": "Statistics"},
  {"name": "Prof. Muhammad Azam Mughal", "designation": "Assistant Professor", "subject": ""},
  {"name": "Prof. Gulzar Ahmad", "designation": "Assistant Professor", "subject": "Statistics"},
  {"name": "Prof. Faiza Iftekhar", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Tuseef Ahmad", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Samad Yaseen", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Syed Zubair Naeem", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Fahad Aziz", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Maryam Aslam", "designation": "Lecturer", "subject": "Statistics"},
  {"name": "Prof. Tehmina Akhtar", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Tahira Ghafoor", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Sumayya Mohsin", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Aeman Sehar", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Amir-ul-Nisa", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Muhammad Usman", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Farhan Mahmood", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Rabia Hussain", "designation": "Lecturer", "subject": "Statistics"},
  {"name": "Prof. Madiha Aqsa", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Misbah Rani", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Sidra Kanwal", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Farah Mushtaq", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Zarmeen Malik", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Mehmood ul Hassan Abbasi", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Bushra Zahoor", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Zunaira Abbas", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Muhammad Naseer-ul-Hassan", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Muhammad Tauseef", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Hafiz Zafar Mehmood", "designation": "Lecturer", "subject": ""},
  {"name": "Dr. Ayesha Qureshi", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Rabia Noreen", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Samaviya Akhtar", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Ahmad Taib Arif", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Arsalan Iftikhar", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Zarafshan Nawaz", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Noor ul Aen", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Muhammad Sajid", "designation": "Lecturer", "subject": ""},
  {"name": "Prof. Iram Naz", "designation": "Lecturer", "subject": ""},
  {"name": "Nadeem Nazir", "designation": "Librarian", "subject": ""}
];
