// BS timetables (2026-27), built from:
//  - "Time Table for BS 3rd Semester Session (2025-29) w.e.f. 01-09-2026" (all programmes; signed by the Incharge Time Table)
//  - BS Physics 5th & 7th Semester time table (Physics Dept.)
//  - Faculty of Mathematics timetable (Mathematics Dept.; semester shown by cell colour)
//  - English Dept. timetable 2026-27 (semester shown by cell colour)
//  - Statistics Dept. BS workload (data.json)
// Each entry: [semester (0 = not marked), programme, period, course, code, teacher, room, note]
// "Shared (General Education)" = courses taken by students of several programmes.
const BS_PROGRAMS = ["Computer Science", "Chemistry", "Economics", "English", "Islamic Studies", "Mathematics", "Physics", "Statistics", "Urdu", "Shared (General Education)"];
const BS_TT = [
  [0, "Shared (General Education)", "VI", "General course (semester not marked)", "GE-167", "Prof. Iram Naz", "", "Semester colour not marked on the Mathematics sheet"],
  [1, "English", "III", "English", "ELL-102", "Prof. Syed Zubair Naeem", "", ""],
  [1, "English", "IV", "English", "ELL-101", "Dr. Muhammad Ismaeel", "", ""],
  [1, "Mathematics", "III", "Mathematics", "Math-101", "Prof. Ejaz Sallamat", "", ""],
  [1, "Physics", "III", "Mathematics for Physics", "MPhy-101", "Dr. Ayesha Qureshi", "", ""],
  [1, "Statistics", "I", "Islamiat / Ethics / TQ", "GIST/GETH-101", "Prof. Hafiz Zafar Mehmood", "", ""],
  [1, "Statistics", "II", "English", "GENG-101", "Prof. Zunaira Abbas", "", ""],
  [1, "Statistics", "III", "Calculus / Mathematics", "SMTH-101", "Prof. Iram Naz", "", ""],
  [1, "Statistics", "III", "Probability and Statistics", "MS251", "Prof. Ashar Shahzad", "", ""],
  [1, "Statistics", "IV", "Introduction to Statistics", "Stat-101", "Prof. Rabia Hussain", "Stat-Lab", ""],
  [1, "Statistics", "V", "Quantitative Reasoning", "QR-I", "Prof. Saqib Munawar", "Stat-Lab", ""],
  [1, "Shared (General Education)", "II", "General course", "MD-001", "Prof. Muhammad Sajid", "", ""],
  [1, "Shared (General Education)", "II", "English (GENG-101 section)", "GENG-101", "Prof. Muhammad Azam Mughal", "", "One of three GENG-101 sections"],
  [1, "Shared (General Education)", "II", "English (GENG-101 section)", "GENG-101", "Prof. Aisha Rehmat", "", "One of three GENG-101 sections"],
  [1, "Shared (General Education)", "IV", "Quantitative Reasoning", "GQR-101", "Prof. Iram Naz", "", ""],
  [3, "Computer Science", "I", "Mathematics", "GE-162", "Prof. Misbah Rani", "16", ""],
  [3, "Computer Science", "II", "Introduction to Management", "GE-192", "CTI", "LT-2", ""],
  [3, "Computer Science", "III", "Computer (+ lab CC-221L)", "CC-221", "CTI", "LT-2 / Lab", ""],
  [3, "Computer Science", "IV", "Computer (+ lab CC-211L)", "CC-211", "CTI", "LT-2 / Lab", ""],
  [3, "Computer Science", "V", "Computer (+ lab CC-210L)", "CC-210", "CTI", "LT-2 / Lab", ""],
  [3, "Computer Science", "VI", "Pakistan Studies (3-4)", "GPST-201", "Prof. Arsalan Iftikhar", "LT-2", ""],
  [3, "Computer Science", "VI", "Tarjuma-tul-Quran (2-2)", "HQ-003", "Prof. Abaid Ullah Tariq", "LT-2", ""],
  [3, "Chemistry", "I", "Information & Communication Technology", "GICT-201", "CTI", "LT2", ""],
  [3, "Chemistry", "II", "English", "GENG-201", "Prof. Khuram Dad", "GB3", ""],
  [3, "Chemistry", "III", "Chemistry (+ lab CHEM-247)", "CHEM-246", "Prof. Muhammad Shabbir", "15 / Lab", ""],
  [3, "Chemistry", "IV", "Chemistry", "CHEM-231", "Prof. Fauzia", "15", ""],
  [3, "Chemistry", "V", "Chemistry", "CHEM-216", "Prof. Samreen Sajid Amin", "15", ""],
  [3, "Chemistry", "VI", "Tarjuma-tul-Quran (1-1)", "HQ-003", "Prof. Muhammad Muttaher Bashir", "LT-2", ""],
  [3, "Chemistry", "VI", "Pakistan Studies (3-4)", "GPST-201", "Prof. Muhammad Muttaher Bashir", "15", ""],
  [3, "Economics", "I", "Economics", "ECON-210", "Prof. Amir Zia", "13", ""],
  [3, "Economics", "II", "English", "GENG-201", "Prof. Irum Riaz", "15", ""],
  [3, "Economics", "III", "Economics", "ECON-209", "Prof. Muhammad Tariq Siddique", "13", ""],
  [3, "Economics", "IV", "History", "AHIS-122", "Prof. Muhammad Muttaher Bashir", "13", ""],
  [3, "Economics", "V", "Economics", "ECON-207", "Prof. Muhammad Tariq Siddique", "13", ""],
  [3, "Economics", "VI", "Pakistan Studies (3-4)", "GPST-201", "Prof. Ahmad Taib Arif", "19", ""],
  [3, "Economics", "VI", "Tarjuma-tul-Quran (2-2)", "HQ-003", "Prof. Abaid Ullah Tariq", "LT-2", ""],
  [3, "English", "I", "Information & Communication Technology", "GICT-201", "CTI", "LT2", ""],
  [3, "English", "II", "English", "GENG-201", "Prof. Irum Riaz", "GB3", ""],
  [3, "English", "III", "English", "ELL-104", "Prof. Aisha Rehmat", "GB3", ""],
  [3, "English", "IV", "English", "ELL-203", "Prof. Asif Abbas", "GB3", ""],
  [3, "English", "V", "English", "ELL-201", "Prof. Khuram Dad", "GB3", ""],
  [3, "English", "VI", "Pakistan Studies (3-4)", "GPST-201", "Prof. Naseer Ahmed Ansir", "GB3", ""],
  [3, "English", "VI", "Tarjuma-tul-Quran (1-1)", "HQ-003", "Prof. Abaid Ullah Tariq", "LT-2", ""],
  [3, "Islamic Studies", "I", "Information & Communication Technology", "GICT-201", "CTI", "LT2", ""],
  [3, "Islamic Studies", "II", "English", "GENG-201", "Prof. Irum Riaz", "15", ""],
  [3, "Islamic Studies", "III", "Arabic", "BSIS-200", "Prof. Saeed Ahmed", "14", ""],
  [3, "Islamic Studies", "IV", "Islamiat", "BSIS-201", "Prof. Naseer Ahmed Ansir", "14", ""],
  [3, "Islamic Studies", "V", "Islamiat", "BSIS-202", "Prof. Syed M. Tahir Shah", "14", ""],
  [3, "Islamic Studies", "VI", "Pakistan Studies (3-4)", "GPST-201", "Prof. Ahmad Taib Arif", "19", ""],
  [3, "Islamic Studies", "VI", "Tarjuma-tul-Quran (2-2)", "HQ-003", "Prof. Abaid Ullah Tariq", "LT-2", ""],
  [3, "Mathematics", "I", "Mathematics", "MATH-201", "Dr. Ayesha Qureshi", "PHY-2", ""],
  [3, "Mathematics", "II", "English", "GENG-201", "Prof. Khuram Dad", "15", ""],
  [3, "Mathematics", "III", "Physics", "NPHY-120", "Prof. Sidra Kanwal", "PHY-2", ""],
  [3, "Mathematics", "IV", "Mathematics", "MATH-202", "Prof. Muhammad Sajid", "PHY-2", ""],
  [3, "Mathematics", "V", "Mathematics", "MATH-203", "Prof. Misbah Rani", "PHY-2", ""],
  [3, "Mathematics", "VI", "Pakistan Studies (3-4)", "GPST-201", "Prof. Muhammad Muttaher Bashir", "PHY-2", ""],
  [3, "Mathematics", "VI", "Tarjuma-tul-Quran (1-1)", "HQ-003", "Prof. Abaid Ullah Tariq", "LT-2", ""],
  [3, "Physics", "I", "Information & Communication Technology", "GICT-201", "CTI", "LT2", ""],
  [3, "Physics", "II", "English", "GENG-201", "Prof. Khuram Dad", "15", ""],
  [3, "Physics", "III", "Physics", "Mphy-213", "Prof. Sidra Kanwal", "Phy 1", ""],
  [3, "Physics", "IV", "Physics", "Mphy-221", "Prof. Saima Amjad", "Phy 1", ""],
  [3, "Physics", "V", "Mathematics", "Mphy-203", "Prof. Sumayya Mohsin", "Phy 1", ""],
  [3, "Physics", "VI", "Pakistan Studies (3-4)", "GPST-201", "Prof. Muhammad Muttaher Bashir", "Phy 1", ""],
  [3, "Physics", "VI", "Tarjuma-tul-Quran (1-1)", "HQ-003", "Prof. Abaid Ullah Tariq", "LT-2", ""],
  [3, "Statistics", "I", "Information & Communication Technology", "GICT-201", "CTI", "LT2", ""],
  [3, "Statistics", "II", "English", "GENG-201", "Prof. Khuram Dad", "15", ""],
  [3, "Statistics", "III", "Programming with R", "STAT-203", "Prof. Rabia Hussain", "19", ""],
  [3, "Statistics", "IV", "Regression Analysis", "STAT-201", "Prof. Amin Iqbal", "19", ""],
  [3, "Statistics", "V", "Statistical Methodology", "STAT-202", "Prof. Maryam Aslam", "19", ""],
  [3, "Statistics", "VI", "Pakistan Studies (3-4)", "GPST-201", "Prof. Ahmad Taib Arif", "19", ""],
  [3, "Statistics", "VI", "Tarjuma-tul-Quran (2-2)", "HQ-003", "Prof. Abaid Ullah Tariq", "LT-2", ""],
  [3, "Urdu", "I", "Information & Communication Technology", "GICT-201", "CTI", "LT2", ""],
  [3, "Urdu", "II", "English", "GENG-201", "Prof. Khuram Dad", "15", ""],
  [3, "Urdu", "III", "Urdu", "BSU-201", "Dr. Fayyaz Ahmad Faizi", "Ur 1", ""],
  [3, "Urdu", "IV", "Urdu", "BSU-202", "Dr. Muhammad Nadim Aslam", "Ur 1", ""],
  [3, "Urdu", "V", "Urdu", "BSU-203", "Prof. Tahira Ghafoor", "Ur 1", ""],
  [3, "Urdu", "VI", "Pakistan Studies (3-4)", "GPST-201", "Prof. Ahmad Taib Arif", "19", ""],
  [3, "Urdu", "VI", "Tarjuma-tul-Quran (2-2)", "HQ-003", "Prof. Abaid Ullah Tariq", "LT-2", ""],
  [5, "English", "I", "Foundation of Education", "", "—", "", "No teacher named on the English Dept sheet"],
  [5, "English", "II", "English", "ELL-301", "Prof. Safia Nadeem", "", ""],
  [5, "English", "III", "English", "ELL-302", "Prof. Faiza Yousaf", "", ""],
  [5, "English", "IV", "English", "ELL-303", "Prof. Irum Riaz", "", ""],
  [5, "English", "V", "Communication and Media Studies", "", "Prof. Syed Zubair Naeem", "", ""],
  [5, "Mathematics", "I", "Mathematics", "Math-304", "Prof. Sumayya Mohsin", "Phy-4", "Taught together with Math-402 (7th)"],
  [5, "Mathematics", "II", "Mathematics", "Math-301", "Dr. Ayesha Qureshi", "Phy-4", ""],
  [5, "Mathematics", "III", "Mathematics", "Math-306", "Prof. Nadia Zahir Babur", "BS-12 / Phy-4", ""],
  [5, "Mathematics", "IV", "Mathematics", "Math-305", "Prof. Abdul Jabbar", "Phy-4", ""],
  [5, "Mathematics", "V", "Mathematics", "Math-303", "Dr. Muhammad Raees", "BS-11", ""],
  [5, "Mathematics", "VI", "Mathematics", "Math-302", "Prof. Muhammad Sajid", "", ""],
  [5, "Physics", "I", "Mathematical Methods of Physics-I (MMP-I)", "", "Prof. Muhammad Imran Bashir", "", ""],
  [5, "Physics", "II", "Solid State Physics-I (SSP-I)", "", "Prof. Bibi Hajra", "", ""],
  [5, "Physics", "III", "Electronics-I", "", "Prof. Khalid Iqbal", "", ""],
  [5, "Physics", "IV", "Classical Mechanics", "", "Prof. M. Kamran Saleem", "", ""],
  [5, "Physics", "V", "Computational Physics-I", "", "Prof. Fahad Aziz", "", ""],
  [5, "Physics", "VI", "Physics Lab-II", "", "Prof. Muhammad Asghar", "", ""],
  [5, "Statistics", "I", "Probability and Probability Distributions-I", "Stat-303", "Prof. Gulzar Ahmad", "16", ""],
  [5, "Statistics", "II", "Sampling Techniques-I", "Stat-302", "Prof. Ashar Shahzad", "16", ""],
  [5, "Statistics", "III", "Experimental Design", "Stat-301", "Prof. Javaid Iqbal", "16", ""],
  [7, "English", "I", "English", "ENG-404", "Prof. Malik Muhammad Iqbal", "", ""],
  [7, "English", "II", "English", "ENG-405", "Prof. Sonia Bukhari", "", ""],
  [7, "English", "III", "English", "ENG-402", "Prof. Nazia Latif", "", ""],
  [7, "English", "III", "General course", "GE-461", "Prof. Khuram Dad", "", ""],
  [7, "English", "IV", "English", "ENG-403", "Prof. Faiza Yousaf", "", ""],
  [7, "English", "V", "English", "ENG-401", "Prof. Safia Nadeem", "", ""],
  [7, "Mathematics", "I", "Mathematics", "Math-402", "Prof. Sumayya Mohsin", "Phy-4", "Taught together with Math-304 (5th)"],
  [7, "Mathematics", "II", "Mathematics", "Math-404", "Prof. Abdul Jabbar", "", ""],
  [7, "Mathematics", "II", "Mathematics", "SC-342", "Prof. Ejaz Sallamat", "", ""],
  [7, "Mathematics", "III", "Mathematics", "Math-412", "Prof. Misbah Rani", "BS-12", ""],
  [7, "Mathematics", "IV", "Mathematics", "Math-403", "Dr. Muhammad Raees", "BS-11", ""],
  [7, "Mathematics", "V", "Mathematics", "Math-401", "Prof. Nadia Zahir Babur", "BS-12", ""],
  [7, "Physics", "I", "Nano Materials and Nano Devices", "", "Prof. Sidra Kanwal", "", ""],
  [7, "Physics", "II", "Quantum Mechanics-II", "", "Prof. Muhammad Asghar", "", ""],
  [7, "Physics", "III", "Statistical Mechanics", "", "Prof. Amir-ul-Nisa", "", ""],
  [7, "Physics", "IV", "Advanced Digital Electronics", "", "Prof. Khalid Iqbal", "", ""],
  [7, "Physics", "V", "Nuclear Physics", "", "Prof. Saima Amjad", "", ""],
  [7, "Physics", "VI", "Classical Electrodynamics", "", "Prof. Muhammad Asif Ali", "", ""],
  [7, "Statistics", "I", "Operation Research", "Stat-412", "Prof. Ashar Shahzad", "17", ""],
  [7, "Statistics", "II", "Time Series Analysis", "Stat-411", "Prof. Saqib Munawar", "17", ""],
  [7, "Statistics", "III", "Statistical Inference-I", "Stat-401", "Prof. Gulzar Ahmad", "17", ""],
  [7, "Statistics", "IV", "Econometrics", "Stat-404", "Prof. Saqib Munawar", "17", ""],
  [7, "Statistics", "V", "Research Methodology", "Stat-406", "Prof. Rabia Hussain", "17", ""],
  [7, "Statistics", "VI", "C++ Comp. Prog. Language", "Stat-405", "Prof. Asif Raza Rizvi", "17", ""]
].map((r) => ({ sem: r[0], program: r[1], period: r[2], course: r[3], code: r[4], teacher: r[5], room: r[6], note: r[7] }));
